consulting:
  description: "Human-in-the-loop; conservative decisions; higher caution."
  thresholds:
    deny_on_any_deny: true
    caution_on_any_caution: true

hybrid:
  description: "Balance of automation and analyst review."
  thresholds:
    deny_on_any_deny: true
    caution_on_any_caution: true

logic-only:
  description: "Pure rule logic; permissive unless redlines fire."
  thresholds:
    deny_on_any_deny: true
    caution_on_any_caution: true

