provider: openai
model: google/gemini-2.5-flash-lite-preview-09-2025
base_url: https://openrouter.ai/api/v1
api_key: sk-or-your-openrouter-key
headers:
  # Optional but recommended by OpenRouter:
  # HTTP-Referer: https://your-site-or-repo
  # X-Title: Idea-Crucible
temperature: 0.2
max_tokens: 800
timeout_s: 30
retries: 2
language: auto # en | zh-CN | auto
