id: RL-008
scope: core
category: moat
condition: "No plausible moat source within target market"
severity: medium
decision: caution
rationale: "Commoditized offerings without defensibility become marginless."
keywords: ["no moat", "commodity", "easy to copy", "no defensibility"]
sources:
  - "Moat taxonomy: data, process embed, network, scale"
owner: core
version: v1
sunset: 2027-12-31
next_steps:
  - "Pursue data network effects, workflow embed, or scale cost curves."

