intent: 做一个benchmark用来评估LLM的意识形态
user: AI 研究员/评估团队
scenario: 构建能量化立场/偏好维度的评测集与度量
triggers: 企业与学界需要透明化的意识形态偏好评估
alts: 常见偏见基准（如BBQ/HellaSwag扩展）、人工标注对比
assumptions:
- 意识形态可操作化为多维指标
- 标注者与地区偏好可校准
- 数据集代表性足够
risks:
- 伦理/合规风险（群体刻板印象）
- 平台政策限制
- 跨文化定义歧义
