intent: CLI tool to convert Markdown to PDF using a well-supported renderer
user: Developers and technical writers
scenario: Local offline conversion with templates and code block syntax highlighting
triggers: Need for consistent document export in CI/CD
alts: Pandoc, VSCode export
assumptions:
- Existing libraries can be composed reliably
- Users want CLI automation
risks:
- Limited differentiation; minor maintenance burden

