intent: 为现场电工提供实时、多模态（语音、视觉）的故障诊断、操作指导和知识检索支持，提高维修效率和准确性。
user: 一线现场电工、维护技术人员。
scenario: 电工在配电室或复杂设备前，双手被占用，通过语音提问或指向设备（视觉输入），AI助手实时分析电路图、设备手册和现场情况，提供分步操作指令或故障排除建议。
triggers: 设备故障报警、需要执行复杂或不熟悉的操作、需要快速查阅技术文档、现场环境光线或操作条件不适合手动操作设备。
alts: 纯语音助手（无视觉辅助）、基于AR眼镜的视觉叠加指导、离线知识库查询系统。
assumptions:
- 电工在现场有稳定的网络连接或可接受的离线模型性能。
- 现场环境噪音水平在可接受的语音识别范围内。
- 电工愿意并习惯于使用语音交互方式进行工作指导。
- 可以获取和整合目标设备（如PLC、变压器）的准确技术文档和图纸。
risks:
- 语音识别在嘈杂工业环境中的准确性挑战。
- 多模态输入（语音+视觉）的实时处理延迟可能影响操作流程。
- 用户对AI建议的过度依赖可能导致关键判断力下降。
- 数据隐私和安全问题，尤其是在处理敏感的工业控制系统信息时。
